[project]
name = "qpp-examples"
version = "0.0.0"
description = "Examples of Quantum Computing in C++ using the Quantum++ library"
platforms = ["linux-64"]
channels = ["conda-forge"]
license = "MIT"
license-file = "LICENSE"

[dependencies]
openmp = ">=8.0"

[build-dependencies]
cmake = ">=4.0"
ninja = ">=1.13"
gxx = ">=15.1"
gdb = ">=16.3"
conda-gcc-specs = ">=15.1"
